[toolchain]
profile = "minimal"
channel = "nightly-2024-12-25"
components = ["rustfmt", "clippy"]
targets = [
    "x86_64-unknown-none",
    "riscv64gc-unknown-none-elf",
    "aarch64-unknown-none",
    "loongarch64-unknown-none-softfloat",
]
